### ISSUE TITLE
I have a problem with api-ai-python

### ISSUE THREAD

**Issue by diegoferbarrios** [api-ai/api-ai-python#11]
*Hi, I have a problem, I can not find a solution,

Can you help me?

When I run the example file:

Say! Press enter for stop audio recording.
Traceback (most recent call last):
File "C:\Users\HP\workspace\audior\audior\raudio.py", line 48, in callback
request.send(data)
File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\query\voice.py", line 56, in send
super(VoiceRequest, self).send(b(newChunk))
File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\request.py", line 112, in send
self.connect()
File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\request.py", line 103, in connect
begin = self._prepage_begin_request_data()
File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\query\voice.py", line 80, in _prepage_begin_request_data
'entities': self._prepare_entities()
File "C:\Users\HP\Anaconda2\lib\json__init.py", line 244, in dumps
return _default_encoder.encode(obj)
File "C:\Users\HP\Anaconda2\lib\json\encoder.py", line 207, in encode
chunks = self.iterencode(o, _one_shot=True)
File "C:\Users\HP\Anaconda2\lib\json\encoder.py", line 270, in iterencode
return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 13: invalid continuation byte
Traceback (most recent call last):
File "C:\Users\HP\workspace\audior\audior\raudio.py", line 91, in 
main()
File "C:\Users\HP\workspace\audior\audior\raudio.py", line 83, in main
p.terminate()
File "C:\Users\HP\Anaconda2\lib\site-packages\pyaudio.py", line 688, in terminate
for stream in self._streams.copy():
TypeError: function takes exactly 5 arguments (0 given)**

**Comment by sstepashka** [comment]
Hello,

Did you change example? (user_entities). Put all file at this issue.
