### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by lowdev** [api-ai/api-ai-python#15]
This the error that i have:

Traceback (most recent call last):
  File "/home/osmc/alfred/robot/stt/api.py", line 50, in callback
    request.send(data)
  File "/usr/local/lib/python2.7/dist-packages/apiai/requests/query/voice.py", line 56, in send
    super(VoiceRequest, self).send(b(newChunk))
  File "/usr/local/lib/python2.7/dist-packages/apiai/requests/request.py", line 112, in send
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/apiai/requests/request.py", line 78, in _connect
    self._connection.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

Pip list : 
apiai (1.0.2)
requests (2.4.3)
urllib3 (1.9.1)

Thanking in advance for any help

**Comment by lowdev** [comment]
This lines do the job: 

import ssl
_create_unverified_https_context = ssl._create_unverified_context
ssl._create_default_https_context = _create_unverified_https_context
