### ISSUE TITLE
Preserve Api.ai SessionId for Dialog Mode

### ISSUE THREAD

**Issue by jhoelzl** [api-ai/api-ai-python#6]
Hello,

i use the [example script](https://github.com/api-ai/api-ai-python/blob/master/examples/send_text_example.py) to send a text request. However, i have a Api.ai Intent that includes a required value, so after the first request i got a question back from Api.ai to specify the value for that intent.

To answer the question, i have to make a new request by using the session_id of the first request. Otherwise the context is reseted: https://docs.api.ai/docs/query

On each request, the [example script](https://github.com/api-ai/api-ai-python/blob/master/examples/send_text_example.py) generates a new session_id.

I tried to specify the session_id on my own, such as:

```
ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN, SUBSCRIPTION_KEY)
request = ai.text_request()
request.lang = lang
request.session_id = "c8819d00-9145-48af-8171-b0489448cded"
request.query = inputtext
response = request.getresponse()
api_resp = response.read()
```

But the additional parameter `session_id` is not used. I think the code in https://github.com/api-ai/api-ai-python/blob/master/apiai/apiai.py#L95 has to be modified.

Can somebody help me?
Thanks!

**Comment by sstepashka** [comment]
Hi, @jhoelzl 

Hm... Maybe. I can debug it tomorrow and resolve your issue. Can you wait? :)
I will message you when done.

**Comment by jhoelzl** [comment]
Hi @sstepashka, thanks, of course i can wait. I have also made a small [pull request](https://github.com/api-ai/api-ai-python/pull/7) into master branch, maybe you can have a look on this when you start the issue.

**Comment by diegoferbarrios** [comment]
Hi, I have a problem, I can not find a solution,

Can you help me?

Say! Press enter for stop audio recording.
Traceback (most recent call last):
  File "C:\Users\HP\workspace\audior\audior\raudio.py", line 48, in callback
    request.send(data)
  File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\query\voice.py", line 56, in send
    super(VoiceRequest, self).send(b(newChunk))
  File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\request.py", line 112, in send
    self._connect()
  File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\request.py", line 103, in _connect
    begin = self._prepage_begin_request_data()
  File "C:\Users\HP\Anaconda2\lib\site-packages\apiai\requests\query\voice.py", line 80, in _prepage_begin_request_data
    'entities': self._prepare_entities()
  File "C:\Users\HP\Anaconda2\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\HP\Anaconda2\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\HP\Anaconda2\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 13: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\HP\workspace\audior\audior\raudio.py", line 91, in <module>
    main()
  File "C:\Users\HP\workspace\audior\audior\raudio.py", line 83, in main
    p.terminate()
  File "C:\Users\HP\Anaconda2\lib\site-packages\pyaudio.py", line 688, in terminate
    for stream in self._streams.copy():
TypeError: function takes exactly 5 arguments (0 given)

**Comment by jhoelzl** [comment]
@diegoferbarrios please open a new issue, your problem is not related to this one.
